name: Build ESPHome Firmware

on:
  workflow_dispatch:
  push:
    paths:
      - '**.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome

      - name: Compile firmware
        run: esphome compile pi-watchdog2.yaml

      - name: List output folder (debug)
        run: ls -l .esphome/build/pi-watchdog2/

      - name: Find firmware file
        run: find . -name firmware.bin

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: pi-watchdog2-firmware
          path: .esphome/build/pi-watchdog2/firmware.bin
