name: Build ESPHome Firmware

on:
  workflow_dispatch:
  push:
    paths:
      - '**.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome

      - name: Compile firmware
        run: esphome compile pi-watchdog2.yaml

      - name: List firmware files
        run: ls -l .pioenvs/**/

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: pi-watchdog2-firmware
          path: .pioenvs/**/firmware.bin
