name: Build ESPHome Firmware

on:
  push:
    paths:
      - '*.yaml'  # ← reagiert auf jede YAML-Datei im Hauptverzeichnisse

jobs:
  build:
    runs-on: ubuntu-latest #comment
    steps:
      - uses: actions/checkout@v3
      - name: Install ESPHome
        run: pip install esphome
      - name: Build firmware
        run: esphome compile pi-watchdog2.yaml
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: pi-watchdog-firmware
          path: .pioenvs/pi-watchdog2/firmware.bin
